version: "3.7"
services:
  
  server:
    build:
      context: .
      dockerfile: ./docker/py/Py.Dockerfile
    ports:
      - "50051:50051"
  
  client:
    build:
      context: .
      dockerfile: ./docker/go/Go.Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - type: bind
        source: ./data
        target: /go/src/ichor/data
    ports:
      - "8080:8080"
