// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GlucoseClient is the client API for Glucose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlucoseClient interface {
	// A simple RPC that obtains a prediction on a future glucose
	// value based on current and past values.
	Predict(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Label, error)
}

type glucoseClient struct {
	cc grpc.ClientConnInterface
}

func NewGlucoseClient(cc grpc.ClientConnInterface) GlucoseClient {
	return &glucoseClient{cc}
}

func (c *glucoseClient) Predict(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Label, error) {
	out := new(Label)
	err := c.cc.Invoke(ctx, "/proto.Glucose/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlucoseServer is the server API for Glucose service.
// All implementations must embed UnimplementedGlucoseServer
// for forward compatibility
type GlucoseServer interface {
	// A simple RPC that obtains a prediction on a future glucose
	// value based on current and past values.
	Predict(context.Context, *Features) (*Label, error)
	mustEmbedUnimplementedGlucoseServer()
}

// UnimplementedGlucoseServer must be embedded to have forward compatible implementations.
type UnimplementedGlucoseServer struct {
}

func (UnimplementedGlucoseServer) Predict(context.Context, *Features) (*Label, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedGlucoseServer) mustEmbedUnimplementedGlucoseServer() {}

// UnsafeGlucoseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlucoseServer will
// result in compilation errors.
type UnsafeGlucoseServer interface {
	mustEmbedUnimplementedGlucoseServer()
}

func RegisterGlucoseServer(s grpc.ServiceRegistrar, srv GlucoseServer) {
	s.RegisterService(&Glucose_ServiceDesc, srv)
}

func _Glucose_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Features)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlucoseServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Glucose/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlucoseServer).Predict(ctx, req.(*Features))
	}
	return interceptor(ctx, in, info, handler)
}

// Glucose_ServiceDesc is the grpc.ServiceDesc for Glucose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Glucose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Glucose",
	HandlerType: (*GlucoseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _Glucose_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "glucose.proto",
}
